services:
  najeewoods_dashboard:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_IMG_URL: ${NEXT_PUBLIC_IMG_URL}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        PORT: ${PORT}
    image: arifbiswas/najeewoods_dashboard:latest
    container_name: najeewoods_dashboard
    ports:
      - 5050:5050
    env_file:
      - .env
      # - ./najeewoods_dashboard/.env
    environment:
      PORT: 5050
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    name: app-network
